### PR TITLE
MLPerf compliance logging

### PR DESCRIPTION
**Pull request by tgrel**
Initial implementation of compliance logging necessary for MLPerf submissions

### CODE REVIEW

**Comment by mnaumovfb** [comment]
Thank you for proposing these changes. Can you please switch this PR from dlrm:master to dlrm:mlperf branch?

**Comment by tgrel** [comment]
Yes, I will do that ASAP.

Also, I'm marking this PR as WIP because there'll be some minor changes required from the dependency on the mlperf compliance library.

**Comment by tgrel** [comment]
Target branch changed. Let's wait for this PR: https://github.com/mlperf/logging/pull/30 to get merged so that I can swap the logging library sources from my fork to the official mlperf compliance repository.

Anyone interested is already welcome to review and comment :)

**Comment by mnaumovfb** [comment]
I have reviewed the files. I think overall it looks fine, but I have couple of questions:

1. in file data_loader_terabyte.py: you rename and introduce a few variables
bytes_per_batch (formerly bytes_per_entry)
num_batches (formerly num_entries)
num_samples (new)
Are these changes cosmetic or do they change the behavior of the code?

2. in file dlrm_s_pytorch.py, line 1055: Can you confirm that the intended operation
epoch_num_float = (j + 1) / len(train_ld) + k + 1
or should it be
epoch_num_float = ((j + **1.0**) / len(train_ld)) + k + 1

3. in file dlrm_s_pytorch.py, line 1230 and 1238: You have changed the stopping criteria from > to >=. We have always run with the former. Is there any particular reason for this subtle change?
(this also impacts the comparison on line 1256)

**Comment by tgrel** [comment]
1. I needed to introduce the num_samples variables to correctly log the number of samples for evaluation and training. I believe having both "samples" and "entries" in the code meaning something different can be confusing. So I replaced "entry" with "batch" everywhere to make the code more readable.

2. In python3 dividing two integers yields a float so these solutions are equivalent. In python2 doing `from __future__ import division` (which is currently done in: https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_pytorch.py#L54) makes the code behave the same as python3. So this works correctly.

3. I'm not particularly attached to this change. I think that having a `>=` condition is more intuitive. This is not a strong opinion and I'm happy to change it if you disagree. This will also require changing the condition here: https://github.com/tgrel/dlrm/blob/tgrel/mlperf_logging/dlrm_s_pytorch.py#L1256

**Comment by tgrel** [comment]
The bug is as follows – if the LR is supposed to be constant after the warmup period but before the decay period. However, in the current implementation if the warmup ends and the decay has not yet started the script crashes with a traceback. I will submit a separate PR by tomorrow morning PST.

**Comment by mnaumovfb** [comment]
Sounds good. Please create a PR for the learning rate fix to dlrm:master branch as we discussed.

Also, I noticed that mlperf/logging#30 has been merged. Please update the logging sources in this PR, so that I can accept it and propagate it to mlperf repo.

**Comment by tgrel** [comment]
@mnaumovfb I've updated the logging library sources. Unfortunately, I also needed to introduce one additional change to make sure everything will be logged correctly. It concerns logging only and shouldn't impact any other functionality, please review and merge if correct. Thanks!

**Pull request merged**
