### PR TITLE
Bweinstein branch - data loading using a torch DataLoader

### PR DESCRIPTION
**Pull request by berryweinst**
Hi,

I've added a Criteo dataset class that is responsible of loading, creating and transforming each sample of the data during the main loop. This change will skip the line-by-line reading overhead. In addition I fixed the main script to use the Criteo data loader. However, the main loop doesn't comply with the synthetic data construct now. You can either make the separate main scripts or adjust the synthetic data set according to the Criteo one.

### CODE REVIEW

**Comment by mnaumovfb** [comment]
Thank you for creating this commit. We really appreciate your comments and suggestions.

We have been thinking about how to improve the data loader as well. The reason why we have implemented loading in its original form was to keep it consistent across multiple inputs as well as PyTorch and Caffe2 versions of the code (not to mention support for CPU and GPU).

We are working on a comprehensive solution that would improve loading time and memory requirements, by providing a similar loading mechanism to your proposal, while keeping it consistent across inputs, frameworks and devices.

Please give us some time to finalize its design and implementation. We'll keep you updated about it.

**Comment by berryweinst** [comment]
Thank you. The code I've suggested is fully compatible with Pytorch (device type included) and I think with caffe2 as well. But please go ahead and use whatever you need from the code.

**Comment by mnaumovfb** [comment]
I have just pushed a commit refactoring the data readers. It incorporates many of the changes you have proposed, but in a slightly different way. 

Please take a look at it and let me know if it resolves your request.

**Comment by berryweinst** [comment]
Thanks, will look at it asap.

**Comment by berryweinst** [comment]
Yes, looks good.

Thanks.

**Comment by mnaumovfb** [comment]
I will close this pull request, because suggested changes have been implemented.

**Pull request closed without merging**
