### PR TITLE
Support ROCm - AMD GPUs on caffe2 backend

### PR DESCRIPTION
**Pull request by rohithkrn**

### CODE REVIEW

**Comment by rohithkrn** [comment]
thanks @xw285cornell . Figuring out on how to sign corporate CLA.

**Comment by mnaumovfb** [comment]
Did you have a chance to sign a corporate CLA? 

I hope you can do it soon, so that we can accept your contribution.

**Comment by rohithkrn** [comment]
Working with our legal team to get it done. Sorry for the delay.

**Comment by rohithkrn** [comment]
@xw285cornell @mnaumovfb signed the CLA.

**Comment by xw285cornell** [comment]
Thanks @rohithkrn!

**Pull request merged**
